# adding tests
# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main, develop, init, "feat/*"]
  pull_request:
    branches: [main, develop, init, "feat/*"]

jobs:
  e2e-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14.x, 16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v3
        # uses: borales/actions-yarn@v3.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install packages with latest npm"
        run: npm i -g npm@latest && npm install
      - name: "Copy .env.example to .env"
        run: cp .env.example .env
      - name: "Start hardhat node"
        run: npx hardhat node & sleep 3
      - name: "List accounts with balances"
        run: npx hardhat accounts
      - name: "Check for solidity linter errors"
        run: npx hardhat check
      - name: "Compile contracts"
        run: npm run compile
      - name: "Check solidity coverage"
        run: npm run coverage
      - name: "Run tests"
        run: npm run test
      - name: "Deploy contracts"
        run: npm run deploy
